### ISSUE TITLE
Scala 2.11 support?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#1]
should we support Scala 2.11 here? (would it be hard?)

in the library ecosystem, I think a lot of libraries will be cross-building to 2.11 for a long while yet

**Comment by julienrf** [comment]
I agree that we should support 2.11. My guess is that it should not be hard because the collections API was quite stable between 2.11 and 2.12, but maybe I miss something?

**Comment by julienrf** [comment]
We should support 2.10 as well, because several projects still support 2.10… (e.g. scalacheck)

**Comment by SethTisue** [comment]
I think we should not support 2.10. Perhaps I could be convinced otherwise, but I think most libraries have already dropped 2.10 support and the remaining ones that haven't, should.

I'm afraid of a garden path here where what we have so far might appear to work in 2.10 relatively easy, but it could get harder later on.

personally (not sure how the rest of the Scala team feels about it), I'm actually interested in actively discouraging continued use of 2.10. I mean, if people are using 2.10 and it's working fine for them then great, more power to you, keep on, but I don't think people on 2.10 _should_ expect brand new stuff like scala-collection-compat to work for them, nor do I think they _do_ expect it

**Comment by adriaanm** [comment]
Agreed on not supporting 2.10

**Comment by julienrf** [comment]
OK, I won’t insist!
