### ISSUE TITLE
Scala.js and native support

### ISSUE THREAD

**Issue by julienrf** [scala/scala-collection-compat#10]
Lots of our most depended on libraries (e.g. scalacheck) support Scala.js or Scala native. We should support these runtimes.

**Comment by SethTisue** [comment]
maybe we could find a volunteer or two to assist with this

**Comment by SethTisue** [comment]
@sjrd did the Scala.js part in #20

**Comment by SethTisue** [comment]
I asked for a Scala Native volunteer: https://gitter.im/scala-native/scala-native?at=5aed7e8997e5506e049c3dc7

**Comment by MasseGuillaume** [comment]
https://github.com/scala/scala-collection-compat/pull/45

**Comment by ekrich** [comment]
Complete for Scala Native - https://github.com/scala/scala-collection-compat/pull/239
