### ISSUE TITLE
Rewrite rule .to[X] => .to(X) is not cross-compatible for Map

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#101]
Currently, the rewrite will do the following patch

```diff
-List((1, 2)).to[Map]: Map[Int, Int]
+List((1, 2)).to(Map): Map[Int, Int]
```

This gives a type error since the `to` function returns an `Iterable[(Int, Int)]`.

The signature of .to[X] is 

```scala
def to[Col[_]](implicit cbf: CanBuildFrom[Nothing, A, Col[A @uV]]): Col[A @uV]
```

https://github.com/scala/scala/blob/90c94cc2ead0b7b1d9ba170da08d27504b2f0fa8/src/library/scala/collection/GenTraversableOnce.scala#L668

Because of the `Col[A]` it's not possible to use to in order to create a `Map[Int, Int]`. We should guard for similar types: `BitSet`, `SortedMap`, etc and convert to the expected type.

```diff
-List((1, 2)).to[Map]: Map[Int, Int]
+List((1, 2)).to(Map).toMap: Map[Int, Int]
```

**Comment by julienrf** [comment]
We should not produce `.to(Map).toMap`. Just `.toMap` is enough. But there will be no `.toXxx` methods for `BitSet` or `SortedMap`… Those cases can not be rewritten.

**Comment by MasseGuillaume** [comment]
It's not possible to write `xs.to[Map]`. The solution is to write `Map.from(xs)` and provide the from method in scala < 2.13.
