### ISSUE TITLE
Rewrite FooBarLike to FooBar

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#105]
For example `MapLike[K, V]` to `Map[K, V]`

https://github.com/akka/akka/pull/25267/files#diff-488ceccab47a0c7eea1440b7cb2df9bbL52

**Comment by julienrf** [comment]
This is not equivalent, I don’t think we should do that in a rewrite rule.

**Comment by MasseGuillaume** [comment]
Maybe as a Roughly rule?

**Comment by julienrf** [comment]
I’m not sure this would provide benefits to the users.
