### ISSUE TITLE
scala-collection-compat is not available

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#132]
1) There is no new version published, the last one is (v0.1.1) is 100 commits ago

2) Since we split the migration in multiple files, it's not possible to distribute migration rules via the only distribution mechanism in scalafix 0.5.10 (via GitHub). I forked 0.5.10 to add the sbt plugin settings `scalafixDepedencies`. This should be available in scalafix 0.6.0 (https://github.com/scalacenter/sbt-scalafix/issues/7) (ETA: August 20th).

This is what I do to use scala-collection-compat on akka:

```bash
# Build 0.2.0-SNAPSHOT
git clone https://github.com/scala/scala-collection-compat
pushd scala-collection-compat
sbt publishLocal
popd

# Build 0.5.10-1-aed3e830
git clone git@github.com:MasseGuillaume/scalafix.git
pushd
sbt publishLocal
popd
```

Then you can use it like this:

project/plugins.sbt

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10-1-aed3e830")
```

build.sbt

```scala
import scalafix.sbt.ScalafixPlugin.autoImport.scalafixDepedencies
lazy val scalaCollectionCompatVersion = "0.2.0-SNAPSHOT"
scalacOptions += "-Yrangepos"
scalafixDepedencies += "org.scala-lang.modules" % "scala-collection-migrations" % scalaCollectionCompatVersion
libraryDependencies += "org.scala-lang.modules" %% "scala-collection-compat" % collectionCompatVersion
```

**Comment by julienrf** [comment]
Note that we can still publish a new version of the `scala-collection-compat` *library* (it works with 2.13.0-M4), if needed.
