### ISSUE TITLE
Setup release infrastructure

### ISSUE THREAD

**Issue by julienrf** [scala/scala-collection-compat#16]

**Comment by lrytz** [comment]
I can take care of that, at least for the compat library part. We have some useful scripts in other repos to do tag driven releases on travis.

**Comment by julienrf** [comment]
Thanks Lukas! In case you were wondering there is nothing to do to “release” the Scalafix migration rule because Scalafix can download it directly from GitHub. This issue is just about releasing the `scala-collection-compat` artifact.

**Comment by lrytz** [comment]
Thanks for raising the issue! Agree on all points.

> we can't publish collections-compat until after Scala.js had been published

We could publish the JVM version earlier in case Scala.js for M4 takes a while to be ready.
