### ISSUE TITLE
scala-collection-migrations missing from maven central

### ISSUE THREAD

**Issue by pjfanning** [scala/scala-collection-compat#160]
I was trying to use https://github.com/scala/scala-collection-compat#migration-tool to migrate the Slick code base and ran into some issues.

One minor issue is that the [docs](https://github.com/scala/scala-collection-compat#migration-tool) say to use scala-collection-compat 0.2.1 but http://central.maven.org/maven2/org/scala-lang/modules/ only has 0.2.0.

A bigger issue is that there doesn't appear to be any scala-collection-migrations jar published in maven central. Is it published to a different repo?

**Comment by julienrf** [comment]
Hi, thanks for trying to run the migration tool! Unfortunately the migration rules are not published yet. This should be fixed by #159.
