### ISSUE TITLE
Release 0.2.1?

### ISSUE THREAD

**Issue by raboof** [scala/scala-collection-compat#161]
It seems for 'cross-compat' migrations of libraries to Scala 2.13.0-M5, it would be good to release 0.2.1.

Is there anything that needs to happen before this can be done?

**Comment by julienrf** [comment]
Hey @raboof! We will release it after it has been upgraded to scalafix 0.9. Would you be interested in helping doing that? There are two wip PRs related to that: #159 and #155.

**Comment by olafurpg** [comment]
I can take care of upgrading scalafix tomorrow, been pushing it back for too long 😅

**Comment by SethTisue** [comment]
0.2.1 scala-collection-compat artifacts are now on their way to Maven Central

but the scala-collection-migration artifacts failed POM validation:

```
Event: Failed: POM Validation
Tuesday, October 23, 2018 08:52:47 EDT (GMT-0400)
typeId    pom-staging
failureMessage    Invalid POM: /org/scala-lang/modules/scala-collection-migrations_2.12/0.2.1/scala-collection-migrations_2.12-0.2.1.pom: Project URL missing, License information missing, SCM URL missing, Developer information missing
```

**Comment by julienrf** [comment]
It should now be available on maven central!
