### ISSUE TITLE
question: good replacement for TraversableLike[X, Y]

### ISSUE THREAD

**Issue by pjfanning** [scala/scala-collection-compat#167]
I used the migration tool on play-iteratees (just as an experiment, I'm not a member of the Play team).
One issue is that the code has a lot of uses of TraversableLike which is removed in scala 2.13 and the migration tool has no rule to migrate this usage.

https://github.com/playframework/play-iteratees/blob/master/iteratees/src/main/scala/play/api/libs/iteratee/Enumeratee.scala#L65

Would anyone have any suggestions what a good replacement would be (while maintaining binary compatibility for scala 2.11 and 2.12)?

**Comment by julienrf** [comment]
If you want to keep compatibility with older Scala versions, use Iterable[X]. Otherwise, IterableOps[X, Iterable, Y].

**Comment by szeiger** [comment]
This works in 2.13: `implicitly[List[Int] => scala.collection.IterableOps[Int, Any, List[Int]]]`

But I doubt we can make it available as a type alias in collection-compat. Depending on the use you would need `Any`, `Nothing` or a correct type constructor as `CC`.
