### ISSUE TITLE
Add `CrossCompat` migration rule that produces code which cross-compiles with 2.12-

### ISSUE THREAD

**Issue by julienrf** [scala/scala-collection-compat#19]
The `NewCollections` migration rule produces code that only compiles with Scala 2.13.0. This is fine for applications, but libraries usually cross compile to several Scala versions.

We should add another migration rule (e.g. `CrossCompat`), which would produce code that happily cross-compiles with all the Scala versions supported by the `scala-collection-compat` module.

Compared to the `NewCollections` rule, the `CrossCompat` rule should:
- apply a subset of the rewrites that produces code compiling with 2.12-, or code supported by the compat library,
- add an import to `scala.collection.compat._` when necessary.

**Comment by MasseGuillaume** [comment]
If a migration can be cross-compiled (for example, CanBuildFrom), do you want to have two versions of that migration: one that compiles only to 2.13 and one that cross-compile?

**Comment by julienrf** [comment]
@MasseGuillaume the `CanBuildFrom` migration does not produce code that compiles with 2.12. You have to add an `import scala.collection.compat._` first to be able to compile the code on 2.12. Therefore, I think the `CrossCompat` migration rule should reuse the same `CanBuildFrom` migration rule, but add the required import to make it compile with 2.12. Does that make sense?
