### ISSUE TITLE
Queue.enqueue

### ISSUE THREAD

**Issue by denisgarci** [scala/scala-collection-compat#209]
In Scala 2.12  `Queue.enqueue` can take an `Iterable`, it's been replaced by `Queue.enqueueAll` in Scala 2.13.

https://www.scala-lang.org/api/current/scala/collection/immutable/Queue.html#enqueue[B%3E:A](iter:scala.collection.immutable.Iterable[B]):scala.collection.immutable.Queue[B]
https://www.scala-lang.org/api/2.13.0-RC2/scala/collection/immutable/Queue.html#enqueueAll[B%3E:A](iter:Iterable[B]):scala.collection.immutable.Queue[B]

**Comment by NthPortal** [comment]
seems like we probably just need an extension method in 2.12
