### ISSUE TITLE
Different behaviors when using to(Map)

### ISSUE THREAD

**Issue by renatocaval** [scala/scala-collection-compat#223]
I noticed that the following 

```scala
import scala.collection.compat._
val ys = Seq(1 -> "a", 2 -> "b")
val m: Map[Int, String] = m.to(Map)
```
Doesn't compile for 2.11 and 2.12 because `to(Map)` returns a `Iterable[(Int, String)]` instead.

The same compiles correctly in Scala 2.13 REPL.

```scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> val ys = Seq(1 -> "a", 2 -> "b")
ys: Seq[(Int, String)] = List((1,a), (2,b))
scala> ys.to(Map)
res0: scala.collection.immutable.Map[Int,String] = Map(1 -> a, 2 -> b)
```

This test https://github.com/scala/scala-collection-compat/blob/master/compat/src/test/scala/test/scala/collection/CollectionTest.scala#L37-L42 seems to indicate that this is a known issue. 

I had hit it while porting `play-slick` to Scala 2.13 (https://github.com/playframework/play-slick/pull/483/files#r295370176).

I didn't look further to the real causes of it, but I will assume this is something that needs fixing.

**Comment by julienrf** [comment]
A workaround would be to call `.toMap`. Would that work for you?

**Comment by renatocaval** [comment]
True, like old times. I don't know why I haven't done that. I think VS Code show me an error and I got to think that this was removed in favour of `to(Map)`.

If you want to close this is issue, fine by me. There still a different behaviour between 2.13 and the compat lib, but maybe not worth the effort.

**Comment by NthPortal** [comment]
I believe the reason it doesn't return a `Map` is the same reason you can't do `to[Map]` in 2.12 or 2.11 - the type constructor for `Map` has two parameters (i.e. `Map[_, _]`), but `to` expects a type constructor with a single parameter (`Col[_]`). Thus, `to(Map)` only works at all because it upcasts the type to `Iterable[(_, _)]`, which has a single type parameter.
