### ISSUE TITLE
scala.jdk package isn't published

### ISSUE THREAD

**Issue by nrinaudo** [scala/scala-collection-compat#224]
# Steps to reproduce

Using either the artifacts published for 2.1.0, or grabbing those created by running `sbt publishLocal`, list the files found in the Scala 2.12 artifact.

# Expected behaviour

The content of package `scala.jdk` should be there - it gets compiled *and* packaged.
Run the following commands to confirm:
* `sbt package`
* `unzip -l .cross/compat212/jvm/target/scala-2.12/scala-collection-compat_2.12-0.1.0-SNAPSHOT.jar`

# Observed behaviour

The content of package `scala.jdk` is not there.

**Comment by nehaev** [comment]
2.1.1 seems to be released. But why it's not published to maven central yet? See https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/

**Comment by dwijnand** [comment]
I'm getting Sonatype permissions for Maven Central, which are taking a little time.

**Comment by nehaev** [comment]
Thanks for the update @dwijnand! Good luck with getting these permissions!

**Comment by dwijnand** [comment]
I got the permissions and released the Sonatype repo, so it should appear sometime soon in https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/ (and the other artefacts).
