### ISSUE TITLE
Missing 2.1.2 release of scala-collection-migrations on Mavenrepository

### ISSUE THREAD

**Issue by BalmungSan** [scala/scala-collection-compat#245]
The [**README**](https://github.com/scala/scala-collection-compat/blob/master/README.md#collection213upgrade) suggest to use the `2.1.2` version of the `"org.scala-lang.modules" %% "scala-collection-migrations"` scalafix dependency.
However, such release does not exist in the [**Mavenrepository**](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-collection-migrations).
Resulting the following error:

```
com.geirsson.coursiersmall.ResolutionException: Failed to resolve Settings(
  dependencies  = List(Dependency("ch.epfl.scala", "scalafix-cli_2.12.8", "0.9.5"), Dependency("org.scala-lang.modules", "scala-collection-migrations_2.12", "2.1.2"))
  repositories  = List(Ivy2Local, Maven("https://repo1.maven.org/maven2"), Maven("https://oss.sonatype.org/content/repositories/releases"), Maven("https://oss.sonatype.org/content/repositories/snapshots"))
  ttl           = Some(Duration.Inf)
  forceVersions = List(Dependency("ch.epfl.scala", "scalafix-cli_2.12.8", "0.9.5"))
)
Dependency 'org.scala-lang.modules:scala-collection-migrations_2.12:2.1.2'
  not found: /home/balmungsan/.ivy2/local/org.scala-lang.modules/scala-collection-migrations_2.12/2.1.2/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-migrations_2.12/2.1.2/scala-collection-migrations_2.12-2.1.2.pom
  not found: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/modules/scala-collection-migrations_2.12/2.1.2/scala-collection-migrations_2.12-2.1.2.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/modules/scala-collection-migrations_2.12/2.1.2/scala-collection-migrations_2.12-2.1.2.pom
```

I am not sure if the problem is that the version is really missing, or if the **README** is misleading in its suggestion.

**Comment by julienrf** [comment]
Thanks for the report. I believe that the version 2.1.2 is missing. Looking at the CI script, it seems that only the `compat` library module is published, not the migration rules.

**Comment by lavrov** [comment]
It's still not published.

**Comment by julienrf** [comment]
I believe this has been fixed by #252 but we have to wait for the next release. In the meantime you can use the previous version, the migration rules haven’t been modified IIRC.

**Comment by lavrov** [comment]
Thanks, I will wait.

(Btw searching on maven gives no results as if it has not been published at all)

**Comment by julienrf** [comment]
I see those results: https://search.maven.org/search?q=g:org.scala-lang.modules%20AND%20a:scala-collection-migrations_2.12&core=gav

**Comment by SethTisue** [comment]
#264 fixed the (semi-)incorrect readme

**Comment by SethTisue** [comment]
2.1.3 is now published (including scala-collection-migrations)
