### ISSUE TITLE
.to(mutable.PriorityQueue) not compiling on 2.12

### ISSUE THREAD

**Issue by fdietze** [scala/scala-collection-compat#247]
I'm porting Scala.rx to 2.13 (https://github.com/lihaoyi/scala.rx/pull/138). It now compiles for 2.13, but not for 2.12 anymore (https://travis-ci.org/lihaoyi/scala.rx/builds/579881994?utm_source=github_status&utm_medium=notification):
```
[error]      type mismatch;
[error]       found   : scala.collection.mutable.PriorityQueue.type
[error]       required: scala.collection.generic.CanBuildFrom[Nothing,rx.Rx.Dynamic[_],scala.collection.mutable.PriorityQueue[rx.Rx.Dynamic[_]]]
[error]      L44:       args.iterator.flatMap(_.v.downStream).to(mutable.PriorityQueue),
```

Am I doing something wrong?

**Comment by julienrf** [comment]
That’s our fault: https://scastie.scala-lang.org/wuOulN8JS2WQTIcveEtgLQ

We should add an implicit conversion to `CanBuildFrom` for companion objects extending `GenericOrderedCompanion` (we currently support [`GenericCompanion`](https://github.com/scala/scala-collection-compat/blob/1ef0ccec53ee8a18e7bf8e0918e079f12747e01b/compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala#L48) and [`SortedSetFactory`](https://github.com/scala/scala-collection-compat/blob/1ef0ccec53ee8a18e7bf8e0918e079f12747e01b/compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala#L60) only).
