### ISSUE TITLE
Rewrite ArrayBuilder.make() -> ArrayBuilder.make

### ISSUE THREAD

**Issue by lrytz** [scala/scala-collection-compat#25]

**Comment by MasseGuillaume** [comment]
also:

```
Iterator.empty.next
Iterator.empty.next()
```

we should create an exhaustive list.

**Comment by julienrf** [comment]
@MasseGuillaume We’ve started an exhaustive list in the [FAQ](https://github.com/scala/collection-strawman/wiki/FAQ).
