### ISSUE TITLE
release 2.1.3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#276]
for two reasons:
* we should (as @ekrich has pointed out) publish for Scala.js 1.0.0-RC1
* to address #245 (scala-collection-migrations didn't publish successfully when we did 2.1.2)

this will be the first time we release this module with sbt-ci-release instead of the old module releasing process, so I'm half expecting it will go wrong. and there are some ways in which it might go wrong that would still involve scala-steward jumping on it before you can say "holy runaway automation, Batman"

so I'd like to do a 2.1.3-RC1 first, see if everything publishes, and have Eric verify that the artifacts are usable with Scala.js 1.0.0-RC1. if that all goes well, I'll follow up with a proper 2.1.3 release

(2.1.2 release ticket was #214)

**Comment by SethTisue** [comment]
> this will be the first time we release this module with sbt-ci-release instead of the old module releasing process, so I'm half expecting it will go wrong

though I see now that @lrytz already did a v2.1.3-TEST at https://travis-ci.org/scala/scala-collection-compat/builds/585968641 (history at #252, #255). that's encouraging. regardless, I would like to do an RC

**Comment by SethTisue** [comment]
* tag: https://github.com/scala/scala-collection-compat/releases/tag/v2.1.3-RC1
* release build: https://travis-ci.org/scala/scala-collection-compat/builds/623505472

gah `[error] java.io.FileNotFoundException: /home/travis/.sbt/gpg/secring.asc (No such file or directory)`

**Comment by SethTisue** [comment]
it's about my bedtime. @lrytz perhaps you could take a look if you're not too busy, since you've been over this before. otherwise I'll come back to it myself (I am no longer underwater, I have a decent amount of time this week and next)

**Comment by lrytz** [comment]
Ah, also in the travis log:

The good version has:

```
Running CI: 
compat211/clean
compat211/test
compat211/publishLocal
set pgpSecretRing := pgpSecretRing.value
set pgpPublicRing := pgpPublicRing.value
compat211/publishSigned
sonatypePrepare
sonatypeBundleUpload
sonatypeClose
```


The bad one:

```
Running CI: 
compat211/clean
compat211/test
compat211/publishLocal
compat211/publishSigned
sonatypePrepare
sonatypeBundleUpload
sonatypeClose
```

So it's indeed the workaround that's missing.

**Comment by lrytz** [comment]
travis-test worked. but i just saw now that this repository doesn't use the `ci-release` task, but replicates its implementation to some degree (https://github.com/scala/scala-collection-compat/blob/master/build.sbt#L348-L359). So the workaround removed in https://github.com/scala/scala-collection-compat/commit/600dba3b0f8ce30d012b422d7f6e66bd7e700ae6#diff-fdc3abdfd754eeb24090dbd90aeec2ce actually needs to stay. It seems I never tested it after removing it... Sorry!

**Comment by lrytz** [comment]
Tagged an v2.1.3-RC2, and the builds look fine: https://travis-ci.org/scala/scala-collection-compat/builds/623598336

I left the staging repos in place, here's a screenshot:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/119636/70614660-39e8d680-1c0b-11ea-88e5-728097845568.png">

**Comment by ekrich** [comment]
@lrytz I just wanted to let you know that the Travis file looks super good. I wish somehow we could use a Travis file like that with `sbt-ci-release` out of the box but `sbt-ci-release` uses Travis Stages in its example. 

This is my solution using Stages - https://github.com/ekrich/sconfig/blob/topic/sjs10rc1/.travis.yml
As you can see, it is not elegant.

If we could figure out how to use `sbt-ci-release` with a Travis file like your in an idiomatic way without the extra code in the sbt file we could make everyone's life easier.

This would make a formula that anyone could copy and tweak and make this publishing easy and fast. cc/ @SethTisue 

Even @tpolecat would be happy.

**Comment by lrytz** [comment]
@ekrich the `build.sbt` file in this repo is rather complicated for reasons I'm not aware. I just did the minimal change to get ci-release working with it the way I want.

In other modules, we use a pretty standard build.sbt and travis.yml, and the build script actually invokes `sbt ci-release`. See https://github.com/scala/scala-collection-contrib for example. We're not using build stages.

Is this what you're looking for?

**Comment by ekrich** [comment]
@lrytz I am not looking particularly but this was something discussed on different chats about how hard publishing is to do. `sbt-ci-release` really helps but doing a matrix with stages in Travis is unclear to me and it seems that many projects have glue in the `sbt` or a `build.sh` or the like. I am referring to `sbt-ci-release` which is a godsend to many of us - https://github.com/olafurpg/sbt-ci-release

**Comment by SethTisue** [comment]
I just hit "release" on the staging repos, so the 2.1.3-RC2 artifacts should reach Maven Central before long. @ekrich please let us know whether the Scala.js 1.0.0-RC1 artifacts work for you

**Comment by SethTisue** [comment]
(before doing 2.1.3 final we'll also want to make sure that artifacts show up at https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-migrations_2.12/2.1.3/)

**Comment by SethTisue** [comment]
> (before doing 2.1.3 final we'll also want to make sure that artifacts show up at https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-migrations_2.12/2.1.3/)

they didn't. pursuing that at #276

**Comment by lrytz** [comment]
Tried RC3 after https://github.com/scala/scala-collection-compat/pull/281, and while sonatype seems to have some issues right now (getting timeouts, https://travis-ci.org/scala/scala-collection-compat/builds/624058691), at least there seems to be an additional 2.12.8 staging repo, which is promising.

**Comment by SethTisue** [comment]
I re-ran the failed jobs and this resulted in some additional staging repositories. And I see scala-collection-migrations artifacts now. I released all the staging repositories just now; once everything hits Maven Central I'll do one last round of sanity checking, then go back and re-tag as 2.1.3 final.

**Comment by sjrd** [comment]
FYI in the meantime we published the artifacts for Scala.js 1.0.0-RC2. The announcement should be up tomorrow.

**Comment by SethTisue** [comment]
The 2.1.3-RC3 artifacts on Maven Central are okay afaict, and on Gitter, @ekrich said he'd tried the 2.1.3-RC2 artifact with Scala.js 1.0.0-RC1 and had trouble, but didn't think the trouble was because the artifact was bad.

And, I merged #278, so we can publish for Scala.js 1.0.0-RC2 instead of RC1.

I'll go ahead and publish now.

**Comment by ekrich** [comment]
The RC2 worked fine once I worked out the Scala.js issues. Thanks, looking forward to the new version.

**Comment by SethTisue** [comment]
(yawns, stretches, puts on a cup of tea)

okay, where were we?

* `git tag -a v2.1.3 -m "v2.1.3"`
* `git push origin v2.1.3`
* tag, release notes: https://github.com/scala/scala-collection-compat/releases/tag/v2.1.3
  * assembled from `git log v2.1.2..v2.1.3`
* release build: https://travis-ci.org/scala/scala-collection-compat/builds/624349128

**Comment by SethTisue** [comment]
gah, now what, 2.1.3-RC3 is missing from https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/ and 2.1.3 isn't showing up either 😡

digging...

**Comment by ekrich** [comment]
Was just going to comment that I couldn't find JVM 2.12 version.

**Comment by SethTisue** [comment]
since I don't see any clues, I guess we should just try again, although given that this somehow went wrong for 2.1.3-RC3 as well, I'm pessimistic

I re-ran https://travis-ci.org/scala/scala-collection-compat/jobs/624349130 (for possible later tea-leaf-reading, the log from the previous run is at https://gist.github.com/SethTisue/1839a531648df75606055e981613cd6f)

new staging repo is orgscala-lang-2033

released the staging repo

🤞

**Comment by SethTisue** [comment]
yay it worked even though nothing was different
