### ISSUE TITLE
rewrite rule Set#-- => &~ or diff

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-collection-compat#28]
https://github.com/scala/scala/blob/d95b53e188a872cdc4c192e4c0587aa3d36568ec/src/library/scala/collection/Set.scala#L144-L156

**Comment by julienrf** [comment]
Actually, if https://github.com/scala/scala/pull/6782 gets merged we won’t need that rewrite rule.

**Comment by julienrf** [comment]
We can not rewrite `--` to `diff` because their signatures don’t match. We could rewrite it to `xs.toSet -- ys`.

**Comment by MasseGuillaume** [comment]
Let's close this issue since it's a deprecation now: https://github.com/scala/scala/pull/6857
The deprecation meta-ticket is here: https://github.com/scala/scala-collection-compat/issues/44
