### ISSUE TITLE
ChainingOps

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala-collection-compat#286]
One feature of 2.13 I am frequently hitting when cross compiling for 2.11 and 2.12 are [ChainingOps](https://github.com/scala/scala/blob/v2.13.1/src/library/scala/util/ChainingOps.scala#L16) `tap` and `pipe`. Implementing them for 2.12 and 2.11 should be easy, the source 2.13 should work as it is.

Would this be in the scope of this project? I know it is called **collection**-compat and this is not exactly a collection, still I think it is a worthwhile compatibility addition.

If agreed this is in scope for this project, I would be willing to try to prepare a PR.

**Comment by julienrf** [comment]
This is discussed in #219 (and #218).

**Comment by SethTisue** [comment]
This was implemented in #320
