### ISSUE TITLE
publish scala-collection-compat_sjs0.6_2.13.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-collection-compat#29]
https://oss.sonatype.org/content/repositories/releases/org/scala-lang/modules/

<img width="376" alt="screen shot 2018-05-16 at 14 55 36" src="https://user-images.githubusercontent.com/389787/40099040-3d0c5f14-5919-11e8-8b37-37567961755a.png">

**Comment by xuwei-k** [comment]
https://github.com/scala/scala-collection-compat/commit/a4c541363b650f691a5ee3ce5d6cdc4f8bf9cdad

**Comment by lrytz** [comment]
0.1.1 is on maven central http://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_sjs0.6_2.13.0-M4/
