### ISSUE TITLE
scala.jdk.javaapi.CollectionConverters for Scala 2.11/2.12

### ISSUE THREAD

**Issue by ijuma** [scala/scala-collection-compat#346]
`JavaConverters` has been deprecated in Scala 2.13 and the implementation of `scala.jdk.CollectionConverters` in this library doesn't work well from Java. Implementing `scala.jdk.javaapi.CollectionConverters` would mean that Java code can move away from the deprecated `JavaConverters` while supporting Scala 2.11, 2.12 and 2.13.

**Comment by ekrich** [comment]
I guess that would have to be a JVM only artifact?

**Comment by DieBauer** [comment]
@SethTisue can this be closed with #551 ?
