### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#357]
This was delayed while we agonized over whether to rename the library, but that's settled now. (We're sticking with the old name, sadly.)

* [x] Stop dithering about the name
* [x] Merge all open PRs
* [x] Decide on version number (2.1.7 or 2.2.0?)
  * let's go with 2.2.0
* [x] Re-enable Scala Steward
* [x] Upgrade to latest MiMa
* [x] Push the changes through the community build
* [x] Draft release notes
* [x] Tag/publish
  * https://travis-ci.org/github/scala/scala-collection-compat/builds/726084816
* [x] Wait for artifacts to arrive on Maven Central
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.2.0/
* [x] Update version in readme
* [x] ~~See if Scala 2.13.0 release notes need updating~~
* [x] reopen #363 
* [ ] (maybe) Tweet? Blog post?

I looked at the version history and it isn't obvious to me why we went from 2.0.0 to 2.1.0, but then subsequent releases remained 2.1.x. My best guess is that the 2.1.0 choice was made by someone conscious of semver, 2.1.1 was just a bugfix, and then for 2.1.2 I just wasn't thinking and it should have been 2.2.0. (And then after that Julien and Lukas followed suit.)

I think I'm inclined to go back to semver and call this one 2.2.0. (Also, it's been an especially long time since the last release.) Opinions?

**Comment by NthPortal** [comment]
2.2.0 sounds good to me

**Comment by SethTisue** [comment]
opens PRs merged. calling it a night 😴

**Comment by SethTisue** [comment]
artifacts are en route to Maven Central — have been for a few hours now — guess I'l look in on it tomorrow

**Comment by SethTisue** [comment]
artifacts are on Maven Central.

before considering whether to tweet or do a blog post, I'd like to first let Scala Steward do its form of "publicity" and see how things go. I'll set a private todo so I don't forget to consider it.

**Comment by SethTisue** [comment]
I haven't seen any steward PRs for this release — not sure what's up, there. I'll ask the steward-of-the-steward about it early next week, I guess.

Is the release working okay for everybody / somebody / anybody?

**Comment by ekrich** [comment]
I got a Steward and it worked fine. https://github.com/ekrich/sconfig/pull/96

**Comment by SethTisue** [comment]
oh good, maybe I just don't happen to watch any repos that have the dependency :+1:
