### ISSUE TITLE
Add `scala.annotation.unused`

### ISSUE THREAD

**Issue by neko-kai** [scala/scala-collection-compat#369]
Together with the new `scala.annotation.nowarn`, perhaps `@unused` could also be back-ported? It's implementable on 2.11/2.12 via [inheritance from `scala.deprecated`](https://github.com/7mind/izumi/blob/develop/fundamentals/fundamentals-language/src/main/scala_2.11/izumi/fundamentals/platform/language/unused.scala)

**Comment by SethTisue** [comment]
fixed by #373
