### ISSUE TITLE
Using  scala-collection-compat together with silencer-plugin is broken

### ISSUE THREAD

**Issue by sideeffffect** [scala/scala-collection-compat#418]
When you use `scala-collection-compat` library together with the `silencer-plugin` compiler plugin, you get errors like this:
```
[error] /home/runner/work/izumi-reflect/izumi-reflect/izumi-reflect/izumi-reflect/src/main/scala/izumi/reflect/internal/fundamentals/collections/IzMappings.scala:26:4: expected literal string as @nowarn annotation argument
[error]   @nowarn("msg=deprecated")
[error]    ^
```

Workaround is to drop `silencer-plugin`, but that might not be the desired solution.

Related:
https://github.com/zio/izumi-reflect/pull/121
https://github.com/scala/scala-collection-compat/issues/413#issuecomment-767967951
https://github.com/scala/scala-collection-compat/pull/417

/cc @SethTisue @ekrich

**Comment by SethTisue** [comment]
@ghik I assume this would be actionable in your repo, rather than here?

**Comment by ghik** [comment]
@SethTisue looks like it, please report in [silencer](https://github.com/ghik/silencer)
