### ISSUE TITLE
immutable.ArraySeq should not have "update" method

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-collection-compat#419]
not immutable 😇 

- https://github.com/scala/scala/blob/v2.13.4/src/library/scala/collection/immutable/ArraySeq.scala#L475-L513
- https://github.com/scala/scala-collection-compat/blob/v2.4.0/compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/ArraySeq.scala#L177

```
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_275).
Type in expressions for evaluation. Or try :help.

scala> val a = new scala.collection.immutable.ArraySeq.ofInt(Array(1, 2, 3))
val a: collection.immutable.ArraySeq.ofInt = ArraySeq(1, 2, 3)

scala> a(0) = 10
       ^
       error: value update is not a member of collection.immutable.ArraySeq.ofInt
       did you mean updated?
```

```
Welcome to Scala 2.12.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_275).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.compat.immutable.ArraySeq
import scala.collection.compat.immutable.ArraySeq

scala> val a = new ArraySeq.ofInt(Array(1, 2, 3))
a: scala.collection.compat.immutable.ArraySeq.ofInt = ArraySeq(1, 2, 3)

scala> a(0) = 10

scala> a
res1: scala.collection.compat.immutable.ArraySeq.ofInt = ArraySeq(10, 2, 3)
```

**Comment by xuwei-k** [comment]
Should we remove these methods? or add `deprecated` annotations for binary compatibility? 🤔

**Comment by NthPortal** [comment]
do they have an `updated` method as well? (i.e. is it possible this was a typo?) not that it makes a huge difference to how we move forward anyway

**Comment by SethTisue** [comment]
We strictly maintain binary compatibility in this library.

**Comment by NthPortal** [comment]
yes but. now we have an immutable collection that's mutable.

what do we do? clone it to `scala.collection.compat.oops_we_screwed_up.immutable.ArraySeq` with the correct API? deprecate the API and change the implementation to `throw new UnsupportedOperationException` (and add the correct `updated` method)?

**Comment by SethTisue** [comment]
Your second suggestion (deprecating) seems fine to me. This library is used mainly by people who are cross-compiling. Anyone who's cross-compiling has no chance of hitting this, as their code wouldn't compile on 2.13. A few folks might not be cross-compiling but using this simply to get some 2.13 niceties, but the chances of any of those folks accidentally calling `update` seems pretty slim to me. Conclusion: I don't see a justification for sinking work into the `oops_we_screwed_up.immutable.ArraySeq` option.

**Comment by NthPortal** [comment]
it turns out that `update` is only defined on the implementation classes and not on `ArraySeq` itself, so it's actually quite difficult to call in practice
