### ISSUE TITLE
rewrite rule CanBuildFrom -> Factory / BuildFrom

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#43]
* https://github.com/scala/scala-java8-compat/commit/da376f7cdfa26901c804f60dc31b59566b9b76c3#diff-ad204af171a6197e5e15bfb23b296923L95
* https://github.com/milessabin/shapeless/commit/f185aa38b59d34529ef9e4c2dc51e667365376ce#diff-92cc88e8912344dc69c3630509293bcaL279
* https://github.com/kxbmap/configs/pull/31/files#diff-0340fa28e076e8b8ca2747d383db2234L244
* https://github.com/rickynils/scalacheck/pull/391/files#diff-ea5e3ec34755d8364ab814f887d407d8L28
* https://github.com/sbt/sbinary/pull/16/files#diff-60a579068040ea258588de92ad0e7090L44
* https://github.com/scala/scala-xml/pull/222/files#diff-fec682ebd8ed9ec07f11ac0f777afaf8R1
* https://github.com/scalikejdbc/scalikejdbc/pull/887/files#diff-3f2f56bfc366dd7d84d05c2ce86977e7L308

**Comment by julienrf** [comment]
One possible rule would be:
 - replace a `cbf: CanBuildFrom[Nothing, A, That]` parameter (for some `A` and `That` parameters) with a `cbf: Factory[A, That]` parameter (I think it’s better to keep the same name),
 - replace usage of `cbf.apply()` with `cbf.newBuilder`

The rule for `BuildFrom` would be the following:
 - replace a `cbf: CanBuildFrom[Repr, A, That]` parameter (for some `Repr`, `A` and `That` parameters) with a `cbf: BuildFrom[Repr, A, That]` parameter,
 - replace usage of `cbf.apply(repr)` with `cbf.newBuilder(repr)`
    - but in case `cbf.apply()` is called, don’t perform any rewrite!

**Comment by MasseGuillaume** [comment]
What about `fromSpecific`/`fromSpecificIterable`?
