### ISSUE TITLE
[Question] Building the 2.12 library

### ISSUE THREAD

**Issue by tomncooper** [scala/scala-collection-compat#430]
Hi, sorry for posting this in an issue, but I am new to `sbt` and I was wondering how to build the 2.12 version of the compat library?

When I run:
```
sbt:scala-collection-compat> set scalaVersion:="2.12.13"
sbt:scala-collection-compat> package
```
I can build the 2.12 jar but it seems to be empty? Is there another setting I need to change?

**Comment by SethTisue** [comment]
`set scalaVersion ...` only sets it on the root project. Try `set every scalaVersion := "2.12.13"` would work I think, but sbt provides a shortcut: `++2.12.13`

**Comment by SethTisue** [comment]
as for the empty JAR, I saw that as well, but apparently I was looking in the wrong place, I should have been looking in `.cross`, it seems? I'm not that familiar with how the `sbt-*-crossproject` plugins work

```
sbt:scala-collection-compat> show compat212/package
[info] /Users/tisue/scala-collection-compat/.cross/compat212/jvm/target/scala-2.12/scala-collection-compat_2.12-2.4.2+2-6d2c22bf-SNAPSHOT.jar
```

**Comment by SethTisue** [comment]
I'm going to close the issue, but feel free to keep asking questions.

**Comment by tomncooper** [comment]
Thanks @SethTisue, I really appreciate the help!
