### ISSUE TITLE
Release a new version with nowarn removed?

### ISSUE THREAD

**Issue by cjllanwarne** [scala/scala-collection-compat#466]
Is there any chance of a new version to get https://github.com/scala/scala-collection-compat/pull/460 out into a release? 

Right now this import collision is making us jump through some awkward hoops to update our project to 2.12.13, and we could do it much more neatly if this merged ticket was part of an official release.

Thank you!

**Comment by SethTisue** [comment]
Sure, I can do that.

**Comment by SethTisue** [comment]
* [ ] merge outstanding PRs
* [ ] choose version number
* [ ] create the release
* [ ] wait for release build
* [ ] release the staging repos
  * https://oss.sonatype.org/#stagingRepositories
* [ ] artifacts on Maven Central
  * [ ] https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_3/2.4.4/
  * (not a complete list)
* [ ] post-release, bump version in README
