### ISSUE TITLE
IterableOnce missing .iterator

### ISSUE THREAD

**Issue by limansky** [scala/scala-collection-compat#479]
I've started implementing Scala 2.13 support in a project and faced with following issue. We used foldLeft on TraversableOnce. I replaced TraversableOnce with IterableOnce. Now I got:
```
method foldLeft in class IterableOnceExtensionMethods is deprecated (since 2.13.0): Use .iterator.foldLeft instead
```
Once I added `.iterator` call it compiles fine with 2.13, however it brakes 2.12, since IterableOnce for 2.12 doesn't have `.iterator` (only `.toIterator`, which is also deprecated in 2.13). I suppose there is should be an implicit adding `.iterator` to IterableOnce.

**Comment by julienrf** [comment]
Hi @limansky ,your suggestion looks reasonable to me. Would you be interested in contributing it?

**Comment by limansky** [comment]
@julienrf yep, let me try do implement it.

**Comment by limansky** [comment]
@julienrf I've found that's it's incorrect. I just had to import `scala.collection.compat._` instead of IterableOnce only.
