### ISSUE TITLE
Release version 2.6.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#497]
* [x] merge PRs
* [x] choose version number
  * 2.6.0
* [x] run `set every version := "2.6.0"; versionCheck` locally
* [x] create the release
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.6.0
* [x] wait for release build
  * https://github.com/scala/scala-collection-compat/runs/4148617755
* [x] artifacts on Maven Central
  * [x] https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_3/2.6.0/
  * (not a complete list)
* [x] any post-release README edits needed?

**Comment by SethTisue** [comment]
sbt-version-policy wanted this to be 2.6.0 not 2.5.1 so I went along with that.

**Comment by SethTisue** [comment]
fyi @lrytz

**Comment by lrytz** [comment]
Thanks!
