### ISSUE TITLE
scala.jdk.OptionConverters missing?

### ISSUE THREAD

**Issue by haukeh** [scala/scala-collection-compat#532]
Greetings, 

while cross-building with Scala 2.12 and 2.13., I just stumbled upon the fact, that there is no `scala.jdk.OptionConverters` in this library. As `CollectionConverters` is present, I am wondering if there is a specific reason why `OptionConverters` was ommited.  

Prior to Scala 2.13 the standard way to go (I guess) was using [scala-java8-compat](https://github.com/scala/scala-java8-compat)'s `scala.compat.java8.OptionConverters`, so probably the idea was that most people would just keep using that instead of the 2.13 `scala.jdk` import? 

Sorry if this is a weird question. It would be great to hear your opinions on this. 

Best regards,
Hauke

**Comment by lrytz** [comment]
I think it's an oversight / nobody asked or thought about it. https://github.com/scala/scala-collection-compat/pull/217 for reference. A contribution would be welcome!

**Comment by haukeh** [comment]
Thanks for the quick reply, Lukas. I'd be willing to add the missing class(es) and create a PR, in fact I've already tried yesterday evening, but I'm struggling a little bit with the `MultiScalaCrossProject`. As `OptionConverters` references `java.lang.Optional` it would need to be included only for the JVM and for Scala 2.11/2.12. I'm still trying to figure out, in which source directory it would need to be for that to work.
