### ISSUE TITLE
Support for Scala Native 0.5.0-RC1

### ISSUE THREAD

**Issue by ekrich** [scala/scala-collection-compat#645]
In order to proceed towards a stable `0.5.0` version of Scala Native, it would really help to support the `RC` versions. I have a dependency on this library.

Consensus has been pretty consistent that downstream will only support the new version and not `0.4.0` in addition to the new version. I don't speak directly for the community or for Scala Native in a formal sense but this is my understanding.

**Comment by SethTisue** [comment]
There is some discussion on #579 about not upgrading Scala Native. But maybe fresh consideration is needed now that 0.5.0 is coming.

**Comment by ekrich** [comment]
I think the current version could be used for Scala Native 0.4.x and then new versions could support 0.5.0. I wouldn't expect the need to update this library for 0.4.x. My informal poll in the Scala Native community is to directly move forward to 0.5.0. It would be nice to try and get the libraries on the RC releases before 0.5.0 final so we can find issues and have everything ready to go. There are quite a few breaking changes so it is not just changing versions from 0.4.x to 0.5.0-RCx.

**Comment by SethTisue** [comment]
SGTM. You are (or whoever is) welcome to try out the 0.5.0-RCx upgrade in a draft PR.

**Comment by SethTisue** [comment]
let's consolidate at #651
