### ISSUE TITLE
Request release to support Scala Native 0.5.0

### ISSUE THREAD

**Issue by ekrich** [scala/scala-collection-compat#651]
With the recent release of Scala Native `0.5.0`, a new release will be needed.

The Scala Native community has agreed only go forward with `0.5.0` so releasing for `0.4.x` going forward will not be needed. The current release would then be sufficient for the `0.4.x` series with no expected need for new versions.

There is a PR to support the new version - https://github.com/scala/scala-collection-compat/pull/646

cc @SethTisue There is no big rush at this time as there are many blockers to build out the Scala Native community.

**Comment by lihaoyi** [comment]
This is currently blocking MainArgs from updating https://github.com/com-lihaoyi/mainargs/pull/125

**Comment by SethTisue** [comment]
hmm, 

```
2024-04-15 17:22:41.596Z error [SonatypeClient] Activity name:close, started:2024-04-15T17:22:01.262Z  - (SonatypeClient.scala:466)
2024-04-15 17:22:41.597Z error [SonatypeClient]     Failed: signature-staging, failureMessage:No public key: Key with id: (95207460c593b13a) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.  - (SonatypeClient.scala:384)
```

but it seems to me that I did upload the key. I guess I'll re-run the job later in case something just needed time to propagate. and if that doesn't work, I'll assume I did something wrong somewhere and I'll make another new key

**Comment by ekrich** [comment]
Looks like it is here - maybe not propagated yet? https://keyserver.ubuntu.com/pks/lookup?search=95207460c593b13a&fingerprint=on&op=index

**Comment by SethTisue** [comment]
re-run went green; waiting for artifacts to appear on Maven Central

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_native0.5_3/2.12.0/
