### ISSUE TITLE
Find out what we can do to release for jdk6 instead of jdk7

### ISSUE THREAD

**Issue by julienrf** [scala/scala-collection-compat#77]

**Comment by eed3si9n** [comment]
It's not going to be as thorough as comparing the `*.class` files, but sbt 1.2.0 will add [Cross JDK forking](https://github.com/sbt/sbt/pull/4139) `java++` command intended for running forked tests.

**Comment by retronym** [comment]
Can we just run with SBT with Java 8 (or later), and set `javaHome := Some(file("/path/to/java6")`

**Comment by lrytz** [comment]
Good point to run on different jvms. Maybe it's easy to switch to 8 for the publish-signed step, for example with a `scala -e ...` command? Just running `sbt publish-signed` would not work, sbt would re-build the project because the classpath changed.

**Comment by MasseGuillaume** [comment]
I implemented @retronym suggestion: https://github.com/scala/scala-collection-compat/pull/83
