### ISSUE TITLE
Rewrite scala.collection.LinearSeq => scala.collection.immutable.List is incorrect

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-collection-compat#99]
The Subclass of LinearSeq are: `List`, `Stream`, `Queue`, `Stack`.

It would break with the following call at use site:

```scala
class A(v: LinearSeq[Int])

new A(Stream(1))
```

becomes

```scala
class A(v: List[Int])

new A(Stream(1))
// found Steam[Int]
// requires List[Int]
```

**Comment by julienrf** [comment]
We should indeed rewrite only `LinearSeq.apply(...)` to `List.apply(...)`. Occurrences of `LinearSeq` in type position should not be changed. If we want to not change how types are inferred, we could rewrite to `List.apply(...): LinearSeq[X]` instead.

**Comment by MasseGuillaume** [comment]
It Looks like LinearSeq was not removed after all: https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/LinearSeq.scala

Can we just remove the rewrite rule?

**Comment by julienrf** [comment]
Yes.
